byu-oit/handel

lib/services/dynamodb/dynamodb.yml
lib/services/dynamodb/index.js
lib/services/efs/efs.yml
test/services/dynamodb/dynamodb-test.js

Using CloudFormation seems to be a lower maintenance cost, and we
can get contributions from multiple people who might not contribute
if it were only being done in code
resolves #20

Convert DynamoDB to use CloudFormation.

---

bin/handel
lib/handel.js
lib/handelfile/parser-v1.js
lib/services/apigateway/index.js
lib/services/dynamodb/index.js
lib/services/ecs/index.js
lib/services/efs/index.js
lib/util/util.js
test/handelfile/parser-v1-test.js

Previously, we didn't check whether a particular service (like EFS)
was consumable from another service (like API Gateway). Not all
AWS services can be consumed by others, so each service needs to
provide hints about what it produces, as well as what it can
consume. This is provided in the form of output types (such as
environment variables, scripts, etc.), that the service deployer
specifies.
The Handel validation then reads this information from the deployers
as it looks at dependency information, and outputs errors if any
dependencies are specified for incompatible services
Resolves #15

Add producing/consuming checks to service dependency links.

---

lib/handel.js
lib/services/deployers-common.js
lib/services/ecs/ecs-service.yml
lib/services/s3/index.js
lib/services/s3/s3.yml
test/services/s3/s3-test.js

This support is quite bare-bones, and only supports creating a
bucket with versioning. It does not yet support things like
lifecycle, logging, static websites, and notifications.
Resolves #11

Add initial support for S3

---

lib/services/ecs/index.js
test/services/ecs/ecs-test.js

If the stack name is too long it fails, because the ALB target
group has a limit of 32 characters in the name.
This change makes the cluster name different from the stack name
so that we can support this limit.
Fixes #33.

Fix bug where ECS creation fails on ALB target group

---

lib/services/lambda/index.js
lib/services/lambda/lambda-template.yml
test/services/lambda/lambda-test.js

This change adds the initial functionality for the Lambda service.
This service by itself isn't terribly useful unless people are
invoking it. There will be changes made to services like SNS and
Lambda to support events coming from SNS to Lambda.
Resolves #28

Add initial Lambda functionality.

---

lib/services/apigateway/index.js
lib/services/beanstalk/index.js
lib/services/deployers-common.js
lib/services/ecs/index.js
lib/services/lambda/index.js
test/services/deployers-common-test.js

This is just an initial piece of functionality to allow apps to talk to parameter store for their secrets, isolated to just their application namespace specified by the prefix <appname>-<envname>-<servicename>
Resolves #61

Add suport for SSM parameter store in compute services

---

lib/aws/cloudwatch-events-calls.js
lib/services/cloudwatchevent/event-rule-template.yml
lib/services/cloudwatchevent/index.js
lib/services/deployers-common.js
test/aws/cloudwatch-events-calls-test.js
test/services/cloudwatchevent/cloudwatchevent-test.js
test/services/deployers-common-test.js
test/services/lambda/lambda-test.js
test/services/s3/s3-test.js

This adds support for CloudWatch Events, only supporting producing
events to the lambda service. Other services like SNS can be added
on an as-needed basis.
Resolves #64 
Resolves #62

Add initial CloudWatch Events support

---

lib/services/deployers-common.js
test/services/deployers-common-test.js

Previously, we only allowed a service to access its secrets, but
not other services in the same Handel file. This changes opens
up access to any parameter for the app, which would be any parameter
that has a name starting with <appName>.
Resolves #69 
Resolves #70

Update parameter store access to allow the entire app namespace

---

lib/lifecycle/consume-events.js
lib/lifecycle/produce-events.js
package.json

Consume events were having race conditions trying to add permissions
to the same lambda. Each would read that there was no policy doc
there, try to add the doc, then one would overwrite the others.
We could try to lock this, but consume and produce run so fast that
there's no reason they can't be serialized.
Resolves #79

Serialize produce and consume event lifecycle phases.

---

docs/supported-services/s3.rst

It turns out the code already supports the default naming for a
bucket, the docs were just written incorrectly to state that the
bucket_name field was required
Resolves #71

Update docs to show that S3 bucket name is optional

---

docs/supported-services/beanstalk.rst
lib/services/apigateway/index.js
lib/services/beanstalk/beanstalk-instance-role-statements.json
lib/services/beanstalk/beanstalk-service-role-statements.json
lib/services/beanstalk/beanstalk-template.yml
lib/services/beanstalk/index.js
lib/services/deployers-common.js
test/services/beanstalk/beanstalk-test.js

This commit switches to use the ALB in Beanstalk. It supports
HTTP and HTTPS. If you use HTTPS then you must specify a certificate
from the ACM service by ID.

Add support for HTTPS in Beanstalk

---

lib/aws/cloudformation-calls.js
lib/services/apigateway/apigateway-proxy-template.yml
lib/services/apigateway/index.js
lib/services/apigateway/lambda-role-statements.json
lib/services/beanstalk/beanstalk-instance-role-statements.json
lib/services/beanstalk/beanstalk-template.yml
lib/services/beanstalk/index.js
lib/services/deployers-common.js
lib/services/ecs/ecs-service-template.yml
lib/services/ecs/index.js
lib/services/lambda/index.js
lib/services/lambda/lambda-role-statements.json
lib/services/lambda/lambda-template.yml
lib/services/s3/index.js
lib/util/util.js
test/services/apigateway/apigateway-test.js
test/services/beanstalk/beanstalk-test.js
test/services/deployers-common-test.js
test/services/ecs/ecs-test.js
test/services/lambda/lambda-test.js

Previously we were creating roles outside the CloudFormation, but
now we have more dynamic ways of creating the CF, so this is
feasible to do inside the CF now.
Resolves #121

Move Role creation inside the CloudFormation for services.

---

lib/aws/ec2-calls.js
lib/services/deployers-common.js
lib/services/ec2-sg-template.yml
test/aws/ec2-calls-test.js
test/services/deployers-common-test.js

This change puts security group creation inside a CloudFormation
template. This is to allow people to easily see at a glance all
the resources for their app by looking at CloudFormation. If they
want to delete an environment, all they need to do is delete the
templates for that env and all resources will go away.
Resolves #120

Create security groups inside CloudFormation

---

lib/aws/s3-calls.js
lib/services/deployers-common.js
test/aws/s3-calls-test.js
test/services/deployers-common-test.js

Handel's bucket where it stores deployable artifacts will now
only keep the last 5 versions, plus anything newer than 30 days.
Anything older than 30 days will be deleted on every deploy. The
most recent 5 versions will always be kept, however, regardless
of date
Resolves #49 
Resolves #86

Add cleanup policy for uploaded S3 artifacts.

---

.gitignore
docs/index.rst
docs/supported-services/apiaccess.rst
lib/services/apiaccess/index.js
lib/services/apiaccess/organizations-statements.json
package.json
test/services/apiaccess/apiaccess-test.js

This service allows you to grant read-only access to AWS services
in an application. The service doesnt create any resources, it only
returns policy statements for consumption by other Handel services.
The initial service only supports the organizations service. More
can be added as needed.
Resolves #87

Add initial apiaccess service support

---

docs/index.rst
docs/supported-services/redis.rst
lib/services/redis/index.js
lib/services/redis/redis-single-no-repl-template.yml
lib/services/redis/redis-single-repl-template.yml
test/services/redis/redis-test.js

This change adds support for the Redis side of ElastiCache. It
only supports non-cluster-mode at the moment. It also doesnt
yet support snapshot or maintenance window configurations, as well
as restoring redis clusters from snapshots.
Resolves #12

Initial support for Redis, non-cluster mode

---

docs/supported-services/apiaccess.rst
lib/services/apiaccess/beanstalk-statements.json
lib/services/apiaccess/cloudformation-statements.json
lib/services/apiaccess/cloudwatchevents-statements.json
lib/services/apiaccess/codebuild-statements.json
lib/services/apiaccess/codepipeline-statements.json
lib/services/apiaccess/dynamodb-statements.json
lib/services/apiaccess/ec2-statements.json
lib/services/apiaccess/ecs-statements.json
lib/services/apiaccess/efs-statements.json
lib/services/apiaccess/elasticache-statements.json
lib/services/apiaccess/lambda-statements.json
lib/services/apiaccess/loadbalancing-statements.json
lib/services/apiaccess/rds-statements.json
lib/services/apiaccess/route53-statements.json
lib/services/apiaccess/s3-statements.json
lib/services/apiaccess/sns-statements.json
lib/services/apiaccess/sqs-statements.json
lib/services/apiaccess/ssm-statements.json
test/phases/produce-events-test.js
test/services/apiaccess/apiaccess-test.js

This change adds more policies to the apiaccess service. This
service grants apps read-only permissions to introspect certain
services in their AWS accounts. This is useful for things like
Lambdas that audit resources in the AWS account.
Resolves #136

Add more policies to apiaccess service type

---

lib/common/deploy-phase-common.js
lib/services/apigateway/index.js
lib/services/beanstalk/index.js
lib/services/dynamodb/index.js
lib/services/ecs/index.js
lib/services/efs/index.js
lib/services/lambda/index.js
lib/services/memcached/index.js
lib/services/mysql/index.js
lib/services/postgresql/index.js
lib/services/redis/index.js
lib/services/s3/index.js
lib/services/s3staticsite/index.js

This change adds these two tags by default since their values are
present in the Handel file.
Resolves #128

Add 'app' and 'env' tags by default

---

docs/supported-services/s3.rst
lib/services/s3/index.js
lib/services/s3/s3-template.yml
test/services/s3/s3-test.js

This adds the bucket-level ACL's to the S3 service. It should be noted that by AWS specs this applies to the bucket. New objects added to the bucket need there own permissions added. For example if I create a bucket with the ACL PublicRead and then after the bucket is created I add a text file without specifying an ACL or policy the text file _will not_ inherit the PublicRead ACL, the result is a bucket that you can see the object but not access the object.
Hope that all makes sense.
resolves #167

added acl parameter to s3 service

---

lib/common/deploy-phase-common.js
lib/services/beanstalk/deployable-artifact.js
lib/services/ecs/cluster-scaling-lambda/index.js
lib/services/ecs/cluster-scaling-lambda/scaling-lambda-template.yml
lib/services/ecs/ecs-service-template.yml
lib/services/ecs/index.js
test/services/ecs/cluster-scaling-lambda/cluster-scaling-lambda-test.js
test/services/ecs/ecs-test.js

This change adds a Lambda that checks every minute to check whether
clusters need to be scaled up or down. It uses the concept of the
'largest schedulable container' from
http://garbe.io/blog/2017/04/12/a-better-solution-to-ecs-autoscaling/
to decide whether the cluster should scale up, scale down, or stay
put.
Now that this is in place, I've also set the cluster minimum healthy
to 50 percent instead of 0 percent, which will now do deployments
without downtimes. This is still hard-coded for now.

Improve ECS instance-level auto-scaling.

---

lib/aws/ec2-calls.js
lib/services/ecs/index.js
test/aws/ec2-calls-test.js
test/services/ecs/ecs-test.js

Previously we were requiring that the user specify an ECS AMI in the
Handel account config. Now we will dynamically query for the latest
AMI. In the future we may add support for custom ECS AMI names and
owners, but for now we'll just use the default AWS one.
Resolves #188

Use the latest ECS AMI.

---

lib/common/elasticache-deployers-common.js
lib/services/memcached/index.js
lib/services/redis/index.js
test/common/elasticache-deployers-common-test.js

CloudFormation was creating a new cluster on every deploy because
of the random characters appended to the end of the cluster name.
This change removes those random characters and just uses more of
the app and service names.

Fix ElastiCache cluster naming bug

---

docs/supported-services/dynamodb.rst
lib/services/dynamodb/dynamodb-template.yml
lib/services/dynamodb/index.js
test/services/dynamodb/dynamodb-test.js
test/services/ecs/ecs-test.js

This change adds support for local and global secondary indexes.
I'm not terribly familiar with DynamoDB's indexes myself, so there
may be a change or two once people start using this.
Resolves #31

Add initial support for DynamoDB secondary indexes.

---

docs/index.rst
docs/supported-services/iot.rst
docs/supported-services/lambda.rst
lib/common/deploy-phase-common.js
lib/common/iot-deployers-common.js
lib/common/produce-events-phase-common.js
lib/phases/produce-events.js
lib/services/cloudwatchevent/index.js
lib/services/iot/index.js
lib/services/iot/iot-topic-rule-template.yml
lib/services/lambda/index.js
lib/services/sns/index.js
test/common/deploy-phase-common-test.js
test/common/iot-deployers-common-test.js
test/common/produce-events-phase-common-test.js
test/services/iot/iot-test.js
test/services/lambda/lambda-test.js

This change adds initial bare-bones support for the IoT service.
Currently we only support configuring topic rules to go to Lambdas.
We can add more to this service as time goes on and we get more
feature requests.
Resolves #131

Add initial support for IoT service.

---

docs/supported-services/ecs.rst
lib/services/ecs/index.js

This change adds the ability for people to specify an image name
from another place like Docker Hub or Quay.io
Resolves #197

Support ECS custom image names.

---

docs/handel-basics/account-config-file.rst
docs/supported-services/ecs.rst
lib/aws/ssm-calls.js
lib/lifecycles/check.js
lib/services/ecs/cluster-auto-scaling.js
lib/services/ecs/cluster.js
lib/services/ecs/containers.js
lib/services/ecs/ecs-service-template.yml
lib/services/ecs/index.js
lib/services/ecs/routing.js
lib/services/ecs/service-auto-scaling.js
lib/services/ecs/volumes.js
test/test-account-config.yml

This change adds service auto-scaling support for tasks in ECS.
ECS is getting complicated enough that I've done some refactoring
into separate modules for some larger concerns in the deployer.
I would like to start testing some of these pieces in a bit more
fine detail now that ECS is getting more complex, but I haven't
added any additional tests in this PR yet. The current tests are
passing.
Resolves #1

Add initial support for service auto-scaling to ECS service.

---

docs/supported-services/apigateway.rst
lib/services/apigateway/apigateway-proxy-template.yml
lib/services/apigateway/index.js

This will add the BinaryMediaTypes support as requested.
Resolves #223

Add support for adding BinaryMediaTypes to apigateway

---

lib/services/ecs/index.js

We're setting it shorter because we handle the instance-level auto-scaling from a Lambda that runs every minute, so it doesn't make sense to wait for 5 minutes.

Update ECS ASG cooldown to 60 seconds

---

docs/supported-services/beanstalk.rst
docs/supported-services/ecs.rst
lib/services/beanstalk/autoscaling-ebextension-template.yml
lib/services/beanstalk/index.js
lib/services/ecs/ecs-service-template.yml
lib/services/ecs/service-auto-scaling.js

This parameter turns out to be important when balancing auto-scaling.

Add support for evaluation_periods in auto scaling

---

docs/index.rst
docs/supported-services/beanstalk.rst
docs/supported-services/ecs.rst
docs/supported-services/route53zone.rst
docs/supported-services/s3staticsite.rst
lib/aws/route53-calls.js
lib/services/beanstalk/dns-names-ebextension-template.yml
lib/services/beanstalk/index.js
lib/services/ecs/ecs-service-template.yml
lib/services/ecs/index.js
lib/services/ecs/routing.js
lib/services/route53zone/index.js
lib/services/route53zone/route53zone-template.yml
test/aws/route53-calls-test.js
test/services/beanstalk/beanstalk-test.js
test/services/ecs/ecs-test.js
test/services/route53zone/route53zone-test.js

Adds support for a `route53zone` service and for configuring DNS records for Beanstalk and ECS.
Resolves #237 .
The only outstanding thing (which should probably be a separate PR) is adding the ability for services to give messages to the user (separate from the normal logging), so that things like the manual steps for `route53zone` can be explained.

Route53 Support

---

bin/handel
lib/cli/index.js

This adds a '-y' option to the delete action to skip the delete confirmation. This also handles the '-d' debug level debugging option correctly.

Fix delete flags

---

lib/services/route53zone/route53zone-template.yml

The route53zone service wasn't setting it's output environment variables properly, and thus you would get an error like this when depending on one:
```
Error during environment deploy: [/Resources/TaskDefinition/Type/ContainerDefinitions/0/Environment/0/Value] 'null' values are not allowed in templates
```

Depending on route53zone fails

---

docs/supported-services/ecs.rst

The ECS docs still had the docs for the old proposal for how to do DNS config.

Remove outdated DNS docs

---

lib/services/beanstalk/dns-names-ebextension-template.yml

Fixed function calls, since ebextensions don't support the ! shorthand.

Fix issue with using DNS in Beanstalk

---

docs/index.rst
docs/supported-services/kms.rst
lib/services/kms/index.js
lib/services/kms/kms-template.yml
test/services/kms/kms-test.js

This adds support for creating and depending on KMS keys.
By default, it creates an alias for the key, named `alias/<appName>/<envName>/<serviceName>`.
**Future Enhancements:**
- Add support for publishing events whenever the key is rotated.  I'll probably tackle this as part of my work on Payment Manager v2.

Add support for KMS

---

lib/services/ecs/ecs-service-template.yml

This change will allow us to spread the ec2 utilization between cluster members

Use a spread placement strategy for ecs clusters

---

lib/common/deploy-phase-common.js
test/common/deploy-phase-common-test.js

This fixes the parameter store prefix to use the correct value of appName.envName instead of appName.envName.serviceName

Fix parameter store prefix to correct value (no service name)

---

docs/supported-services/apigateway.rst
lib/services/apigateway/swagger/swagger-deploy-type.js
test/services/apigateway/swagger/test-swagger.json

API Gateway supports HTTP passthrough as a choice for handling API gateway resource methods, and this change adds support in Handel to use them. You can mix and match these HTTP passthrough methods and Lambda functions in your Swagger file.

Add support for HTTP passthrough URLs in Swagger documents

---

docs/supported-services/route53zone.rst
docs/supported-services/s3staticsite.rst
lib/services/s3staticsite/index.js
lib/services/s3staticsite/s3-static-site-template.yml
lib/services/s3staticsite/set-ipv6.js
package.json
test/services/s3staticsite/s3staticsite-test.js

By adding CloudFront support, we can now support DNS names and HTTPS certificates on S3 Static Sites.
Fixes #183. Fixes #190.
**Future Work:**
Add a `cloudfront` service type, and support pointing at an s3 static site to allow for more complex configuration.

Support fronting S3 Static Sites with CloudFront

---

lib/services/ecs/index.js

fix null ec2 list when trying to decide if cluster needs a restart after an update when the cluster hasn't been created.

Ecs bug fix

---

docs/supported-services/beanstalk.rst

Adding clarification that "https_certificate" should be "https_certificate: <string>" (like other supported services in Handel)

Typo in Beanstalk Docs

---

src/services/kms/index.js
test/services/kms/kms-test.js

The docs say that auto_rotate defaults to true, but the code has it
default to false. Adds a `hasOwnProperty` check to set the default
properly, as well as tests to check for regressions.

Fix KMS Key Auto-Rotation Default

---

package-lock.json
package.json
src/common/handlebars-utils.js
src/datatypes/service-config.ts
src/datatypes/service-context.ts
src/datatypes/tags.ts
src/services/dynamodb/autoscaling.ts
src/services/dynamodb/config-types.ts
src/services/dynamodb/dynamodb-autoscaling-template.yml
src/services/dynamodb/index.js
test/services/dynamodb/dynamodb-test.js

Cloudwatch has very low API Rate Limits. Turns out, it's pretty easy to
hit that limit when setting up lots of application autoscaling rules in
Cloudformation (see https://forum.serverless.com/t/autoscaling-for-amazon-dynamodb/2071). So, by adding a DependsOn to all of our scaling targets,
we can avoid hitting that rate limit by forcing Cloudformation to only
make one call at a time, rather than parallelizing all of them.
In order to make that happen, I've also restructured the autoscaling
template.  It should produce the same output as before, with added
'DependsOn' attributes, but with a lot less duplication in the
Handlebars template itself. Plus, the new structure makes it a LOT
easier to compute the 'DependsOn' values.

DynamoDB Autoscaling - Use DependsOn to avoid CloudWatch API Rate Limits

---

src/common/deploy-phase-common.js
test/common/deploy-phase-common-test.js

Now, it's just the DEPENDENCY_NAME_VALUE_NAME format.
We've kept the legacy version around for a while; it's about time we
drop it. This is purely unselfish on my part and has no relation to
the fact that I just hit the 4k limit on total env var length on one of
my lambdas. Nope, definitely not.
Speaking of which, we may want to come up with a strategy for dealing
with the fact that many services have a limit on environment variables.

Remove legacy injected env var format.

---

src/services/ecs-fargate/index.js

This change removes the SSH ingress rule from the Fargate security group. You can't access the Fargate EC2 instances, so this rule doesn't make sense to have.

Remove SSH ingress from Fargate security group

---

docs/handel-basics/handel-file.rst
docs/handel-basics/tagging.rst
src/common/deploy-phase-common.ts
src/datatypes/index.ts
src/handelfile/parser-v1.ts
src/handelfile/v1-schema.json
test/common/deploy-phase-common-test.ts
test/handelfile/parser-v1-test.ts

This PR will aim to make it easier to apply tags across all resources in a Handelfile.
For the BYU use case, this makes it easier to have consistent tagging with required tags like 'team' and 'data-sensitivity'.
This gets us part of the way towards solving the issues raised in #332.

Application-level tagging

---

src/services/s3/index.ts

This adds the ability to getObjectAcl and putObjectAcl for services that depend on the s3 service.
@dsw88 Feel free to reject or modify This was just a quick fix for the issues that were being discussed in Slack
resolves #363

added getobjectAcl and putObjectAcl to policy

---

docs/handel-basics/account-config-file.rst
src/account-config/default-account-config.ts
src/aws/aws-tags.ts
src/aws/aws-wrapper.ts
src/aws/cloudformation-calls.ts
src/aws/s3-calls.ts
src/common/deploy-phase-common.ts
src/common/pre-deploy-phase-common.ts
src/common/s3-deployers-common.ts
src/datatypes/index.ts
src/services/ecs/cluster-auto-scaling.ts
test/aws/aws-tags-test.ts
test/aws/s3-calls-test.ts

Fixes #360.
Adds an optional field to the account config file, handel_resource_tags,
which contains tags that Handel will apply to any non-application,
account-wide resources that Handel may create.
This change will not be able to modify any resources that already exist.
Those will either have to be deleted and re-created, or one can manually
add the tags to the cloudformation templates that Handel creates to add
the tags.

Tag handel account-wide resources

---

docs/getting-started/cli-reference.rst
docs/index.rst
package-lock.json
src/cli/index.ts
src/common/tagging-common.ts
src/handel.ts
test/cli/cli-test.ts

Yet another thing related to #332.
Allows the user to pass a -t flag to `handel deploy` with a list of
key-value pairs. These will augment or override any tags that are
specified in the handelfile.

Implement CLI Tag Overrides

---

extension-api/extension-api.ts
extension-api/package-lock.json
extension-api/package.json
extension-api/tsconfig.json
extension-api/tslint.json
handel/package.json
handel/src/datatypes/index.ts
handel/tsconfig.json
lerna.json
package-lock.json
package.json
tsconfig.json

This depends on #371 being merged.
Adds an extension-api package which contains all of the data types needed by the extensions API. This is a subset of the types defined in handel/src/datatypes/index.
The old datatypes file now extends or implements the new one in all cases, which allows us to add internal extensions to anything we need to while enforcing compatibility with the extensions API.
Some thoughts to consider while reviewing:
* Are there any fields in the interfaces that we don't need to be publicly available?
* For the service response types, should we keep them as classes? Right now, they're interfaces, but providing the class version might be nice for people who have to construct them to return from the methods.

Add extension API Types

---

docs/supported-services/apigateway.rst
docs/supported-services/route53zone.rst
handel/package-lock.json
handel/src/services/apigateway/common.ts
handel/src/services/apigateway/config-types.ts
handel/src/services/apigateway/index.ts
handel/src/services/apigateway/proxy/apigateway-proxy-template.yml
handel/src/services/apigateway/proxy/proxy-passthrough-deploy-type.ts
handel/src/services/apigateway/swagger/apigateway-swagger-template.yml
handel/src/services/apigateway/swagger/swagger-deploy-type.ts
handel/test/services/apigateway/apigateway-test.ts
handel/test/services/apigateway/proxy/proxy-passthrough-deploy-type-test.ts
package-lock.json

This resolves #347.
This implements the simplest-possible version of custom domain names.  It only allows for a custom domain name to be used by a single API Gateway, and doesn't allow for path mappings (everything is at /).  If we want to enhance that later, we can.
I also factored some common checking logic between the two API gateway deployers out into the main service file.

API Gateway Custom Domain Support

---

docs/supported-services/dynamodb.rst
handel/src/services/dynamodb/config-types.ts
handel/src/services/dynamodb/index.ts
handel/test/services/dynamodb/dynamodb-test.ts

There may be cases where we need our DDB table to have a specific name.  The specific case I'm dealing with is CAS, which, when integrated with Dynamo, expects tables with certain, non-configurable names to exist.

Allow user to set DynamoDB table names

---

handel/src/services/stepfunctions/index.ts
handel/test/services/stepfunctions/stepfunctions-test.ts

Without these changes, the stepfunctions service only supports 'Task' state type (expecting all states to have a 'Resource' field with a dependency's name.

not checking resources that don't exist

---

handel/src/handel.ts

CLI now uses the appropriate function to parse the tags passed with -t.

Fix problem with parsing CLI tags

---

examples/random-secret-extension/package-lock.json
examples/random-secret-extension/package.json
extension-api/extension-api.ts
handel/src/common/bind-phase-common.ts
handel/src/datatypes/index.ts
handel/src/phases/bind.ts
handel/src/phases/consume-events.ts
handel/src/phases/deploy.ts
handel/src/phases/pre-deploy.ts
handel/src/phases/produce-events.ts
handel/src/phases/un-bind.ts
handel/src/phases/un-deploy.ts
handel/src/phases/un-pre-deploy.ts
handel/test/phases/bind-test.ts

Thanks to Node's super fun module resolution weirdness, the extensions
API in an actual extension might be a different instance than the one in
Handel proper. So, we're ditching instanceof in favor of Duck type
checking ("if it quacks like a duck, it must be a duck!"). Yaaaay node.

Replace instanceof with Duck checks

---

extension-api/extension-api.ts

This will be removed later, but for now we will have account config files out there with account_id as a number.

Allow for account_id to be a number for historical reasons

---

handel/src/extensions-support/npm/index.ts

When trying to create handel extensions on my windows machine we ran into an error where my machine was trying to run npm the linux way and not the windows way. This should check if you're running on windows, if so then it will use the `npm.cmd` instead of `npm`

added support for windows npm

---

extension-api/extension-api.ts
extension-api/tsconfig.json
extension-support/tsconfig.json
handel/src/aws/cloudwatch-events-calls.ts
handel/src/aws/ecs-calls.ts
handel/src/aws/iam-calls.ts
handel/src/aws/lambda-calls.ts
handel/src/aws/route53-calls.ts
handel/src/aws/s3-calls.ts
handel/src/aws/ses-calls.ts
handel/src/aws/sns-calls.ts
handel/src/aws/sqs-calls.ts
handel/src/aws/sts-calls.ts
handel/src/extensions-support/npm-loader.ts
handel/src/extensions-support/resolve-extensions.ts
handel/src/services/dynamodb/autoscaling.ts
handel/src/services/dynamodb/index.ts
handel/src/services/ecs-fargate/index.ts
handel/src/services/ecs/asg-cycling.ts
handel/src/services/ecs/cluster-auto-scaling.ts
handel/src/services/ecs/index.ts
handel/tsconfig.json
lerna.json
package.json
tsconfig.json

We were missing some imports and type definitions here and there in order for TypeScript to allow us to turn on the "declaration: true" flag. 
This change adds those and modifies the tsconfig file to start outputting TypeScript declaration files for all the packages in the repository.
Resolves #418

Modify files necessary to start outputting TS declarations in main project

---

extension-support/package-lock.json
extension-support/package.json
extension-support/src/common/check-phase.ts
extension-support/src/extension-support.ts
extension-support/test/common/check-phase-test.ts
extension-support/test/common/test-json-schema.json
handel/src/services/sns/index.ts
handel/src/services/sns/params-schema.json
handel/src/services/sqs/index.ts
handel/test/services/sns/sns-test.ts

This change adds support for validating service specs against JSON schema documents. This is a more rigorous and complete way of executing the check phase rather than multiple checks in code. Some checks will still need to be done in code of course for validating the semantics of a service configuration, but this should reduce the amount of code required and improve the quality of the check phase.
Other services will be converted to use JSON schema documents in future pull requests.

Add common module for checking JSON schema and convert SNS service

---

handel/src/services/ecs-fargate/ecs-fargate-template.yml

Fixes #320. Fixes #446. We already have a Handlebars helper to turn
anything into a valid CFN logical ID, so I put that into the fargate
template.  We'll probably want to follow up and search for other places
where this would be useful.

Transform container names to CFN Logical ID format

---

handel/src/common/ecs-routing.ts
handel/src/services/apigateway/common.ts
handel/src/services/beanstalk/index.ts
handel/src/services/codedeploy/alb.ts
handel/src/services/lambda/config-types.ts
handel/src/services/s3staticsite/index.ts

This also unifies the message across all places where we're searching
for a zone ID.
It may make more sense to create another method that wraps the
getBestMatchingHostedZone function, which throws if there isn't one.  I
don't necessarily want to do that inside of getBestMatchingHostedZone,
because I can see cases where we'd want to use the falsy-returning
version.  Perhaps a method named 'requireBestMatchingHostedZone'?

Add a nicer message when Route53 zones are missing

---

handel/src/services/s3staticsite/index.ts
handel/test/services/s3staticsite/s3staticsite-test.ts

The S3 Static Site service is currently not consumable by other services like Beanstalk or Lambda. This change makes it consumable, but only in a read-only manner. This will help prevent frustration with writing changes to the bucket but then having them overwritten during the next deploy, while still allowing other services to read the contents in the static site.

Make static site read-only consumable from other services

---

handel/src/aws/route53-calls.ts
handel/src/common/ecs-routing.ts
handel/src/services/apigateway/common.ts
handel/src/services/beanstalk/index.ts
handel/src/services/codedeploy/alb.ts
handel/src/services/s3staticsite/index.ts
handel/test/services/codedeploy/alb-test.ts

This does what I should have done to start and creates a separate method
in route53-calls which throws a consistent error if there isn't a
matching Hosted Zone.

Better solution for #445.

---

handel/src/aws/route53-calls.ts

AWS appears to have pushed out a bad update to Route53 in the last 24 hours. In their API responses, they're now prefixing Hosted Zone IDs with '/hostedzone/', which is breaking anything in Handel that tries to use Route53.
This change looks for that prefix and strips it out if it finds it.  That way, if Amazon rolls back this change, we won't be broken.  We'll want to keep an eye on things and, if they change back, remove this fix.  However, we ought to probably release this quickly so that people can get work done.

Fix issue with AWS Route53 API incompatible change

---

handel/src/aws/route53-calls.ts

This reverts commit aaf1193b216b106e209d3373ffd85028328ac4bb.
Turns out, the Route53 ID stuff was a red herring.  The issue was actually being caused by the fact that the user had deleted the hosted zone that was being referenced manually, so CFN was actually failing when it tried to remove the old record.

Revert "Fix issue with AWS Route53 API incompatible change (#485)"

---

docs/supported-services/dynamodb.rst

it appears the actual default throughput if not specified is actual 1 for read and write. I just deployed a project with the thruput not define and the table is 1.

update dynamodb docs

---

extension-support/package-lock.json
handel/package-lock.json
handel/src/services/dynamodb/autoscaling.ts
handel/src/services/dynamodb/index.ts
handel/test/services/dynamodb/dynamodb-test.ts

If a custom table name is specified, setting up autoscaling on the DDB
table will fail because the autoscaling template references the wrong
table name. This change makes the autoscaling pull the name from the
output of the DDB table's stack.

Fix for #517 - Dynamo DB autoscaling + custom names

---

extension-support/npm-scripts.js
extension-support/package.json
handel/npm-scripts.js
handel/package.json

The changes away from Gulp made the Windows build process break. This commit makes it work on Windows again.
Resolves https://github.com/byu-oit/handel/issues/504

Make build/test process work on Windows

---

handel/src/services/ecs-fargate/ecs-fargate-template.yml
handel/src/services/ecs/ecs-service-template.yml

This change sets the target group deregistration delay to the same number of seconds as the ALB timeout. This seems to make sense because we shouldn't wait longer for connection draining than the default timeout.
Resolves #500

Set ALB target group deregistration delay to same as ALB timeout

---

docs/supported-services/redis.rst
handel/src/services/redis/index.ts

Trying to deploy redis 2.8
`error:   Error during environment deploy: Errors while creating stack 'handel-test-dev-cache-redis': 
CREATE_FAILED : AWS::ElastiCache::CacheCluster : Expected a parameter group of family redis2.8 but found one of family redis2.6 (Service: AmazonElastiCache; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 21df3c82-b78d-11e8-a38f-49c6c30d28ae)`
It was a simple copy/paste error.
I validated that deploying redis 2.8 works after this change.

fixed typo

---

handel/src/services/ecs-fargate/ecs-fargate-template.yml
handel/src/services/ecs/ecs-service-template.yml

Partial fix to #496 . Only works in ECS and ECS Fargate for now, but it should be pretty easy to extend it to every other service that uses ALB.

Add automatic redirects to HTTPS in ecs and fargate

---

handel/src/services/sqs/params-schema.json

Both the docs and the code disagree with this schema. *sigh* dynamic typing is why we can't have nice things.

Make sqs schema match reality

---

extension-support/src/common/deploy-phase.ts
extension-support/test/common/deploy-phase-test.ts
handel/src/services/apigateway/common.ts
handel/src/services/beanstalk/index.ts
handel/src/services/codedeploy/iam-roles.ts
handel/src/services/ecs-fargate/index.ts
handel/src/services/ecs/index.ts
handel/src/services/lambda/index.ts
handel/src/services/stepfunctions/index.ts
handel/test/services/apigateway/common-test.ts
handel/test/services/codedeploy/iam-roles-test.ts

This allows applications to put custom metrics (like, for example, JVM memory stats) to CloudWatch.

Add ability to put metrics to all compute-ish services

---

extension-support/src/common/deploy-phase.ts
extension-support/test/common/deploy-phase-test.ts

This pull fixes an issue where the resource definition in the policy document wasn't an array which caused cloudformation to fail.

Fix putMetrics policy document

---

handel/package-lock.json
handel/package.json

Caporal version 1.2.0 is not working correctly at the moment. More work needs
to be done to figure out why. But in the meantime this pull will fix running
pipelines.

Pin Caporal to 1.1.0

---

.circleci/config.yml
handel/src/services/beanstalk/index.ts

The all at once default takes your app offline as documented here: 
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.rolling-version-deploy.html?shortFooter=true'
Followed the policy syntax here: 
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html?shortFooter=true#command-options-general-elasticbeanstalkcommand

use rolling deploys for beanstalk, instead of the 'all at once' default

---

handel/src/services/beanstalk/beanstalk-instance-role-statements.json

There important permissions missing from the EC2 instance role for beanstalk. Also, CloudWatch doesn't let you apply fine-grained permissions - * for everyone!

Add proper cloudwatch permissions for exporting logs

---

docs/handel-basics/account-config-file.rst
handel/src/services/apigateway/proxy/apigateway-proxy-template.yml
handel/src/services/apigateway/proxy/proxy-passthrough-deploy-type.ts
handel/src/services/apigateway/swagger/apigateway-swagger-template.yml
handel/src/services/apigateway/swagger/swagger-deploy-type.ts
handel/src/services/beanstalk/beanstalk-template.yml
handel/src/services/beanstalk/config-types.ts
handel/src/services/beanstalk/index.ts
handel/src/services/codedeploy/codedeploy-asg-template.handlebars
handel/src/services/codedeploy/config-types.ts
handel/src/services/codedeploy/index.ts
handel/src/services/dynamodb/autoscaling.ts
handel/src/services/dynamodb/dynamodb-autoscaling-template.yml
handel/src/services/ecs-fargate/config-types.ts
handel/src/services/ecs-fargate/ecs-fargate-template.yml
handel/src/services/ecs-fargate/index.ts
handel/src/services/ecs/cluster-auto-scaling.ts
handel/src/services/ecs/cluster-draining-lambda/cluster-draining-template.yml
handel/src/services/ecs/cluster-scaling-lambda/scaling-lambda-template.yml
handel/src/services/ecs/config-types.ts
handel/src/services/ecs/ecs-service-template.yml
handel/src/services/ecs/index.ts
handel/src/services/lambda/config-types.ts
handel/src/services/lambda/index.ts
handel/src/services/lambda/lambda-template.yml
handel/src/services/stepfunctions/config-types.ts
handel/src/services/stepfunctions/index.ts
handel/src/services/stepfunctions/stepfunctions-template.yml

If `permissions_boundary` is in the account config, Handel will add that permissions boundary to each role it creates.

Feature permissions boundary
