byu-oit/handel

- lib/datatypes/bind-context.js
- lib/services/apigateway/index.js
- lib/services/dynamodb/index.js
- lib/services/ecs/index.js
- lib/services/efs/index.js
- lib/services/s3/index.js
- lib/services/sns/index.js
- lib/services/sqs/index.js
- test/datatypes/bind-context-test.js
- test/handel-test.js
- test/lifecycle/bind-test.js
- test/services/sns/sns-test.js
- test/services/sqs/sqs-test.js
> Update BindContext object to include dependentOfServiceContext

- lib/aws/lambda-calls.js
- lib/aws/sns-calls.js
- lib/datatypes/deploy-context.js
- lib/handelfile/parser-v1.js
- lib/lifecycle/consume-events.js
- lib/lifecycle/produce-events.js
- lib/services/lambda/index.js
- lib/services/sns/index.js
- test/aws/lambda-calls-test.js
- test/aws/sns-calls-test.js
- test/datatypes/deploy-context-test.js
- test/handelfile/parser-v1-test.js
- test/lifecycle/consume-events-test.js
- test/lifecycle/produce-events-test.js
- test/services/lambda/lambda-test.js
- test/services/sns/sns-test.js
This change adds the first event consumer/producer relationship in
SNS to Lambda. The general pattern of consume and produce lifecycle
phases is working so far
> Implement SNS -> Lambda events

- lib/services/apigateway/index.js
- lib/services/beanstalk/index.js
- lib/services/deployers-common.js
- lib/services/ecs/index.js
- test/services/deployers-common-test.js
> Inject handel file info in compute services

- bin/handel
- lib/aws/cloudformation-calls.js
- lib/aws/ec2-calls.js
- lib/aws/iam-calls.js
- lib/aws/lambda-calls.js
- lib/aws/s3-calls.js
- lib/aws/sns-calls.js
- lib/handel.js
- lib/lifecycle/bind.js
- lib/lifecycle/check.js
- lib/lifecycle/consume-events.js
- lib/lifecycle/pre-deploy.js
- lib/lifecycle/produce-events.js
- lib/services/apigateway/index.js
- lib/services/beanstalk/index.js
- lib/services/dynamodb/index.js
- lib/services/ecs/index.js
- lib/services/lambda/index.js
- lib/services/s3/index.js
- lib/services/sns/index.js
- lib/services/sqs/index.js
> Make consistent logs and add debug level

- lib/aws/sqs-calls.js
- lib/services/sns/index.js
- lib/services/sqs/index.js
- lib/services/sqs/sqs-template.yml
- test/aws/cloudformation-calls-test.js
- test/aws/ec2-calls-test.js
- test/aws/iam-calls-test.js
- test/aws/lambda-calls-test.js
- test/aws/s3-calls-test.js
- test/aws/sns-calls-test.js
- test/aws/sqs-calls-test.js
- test/services/sqs/sqs-test.js
> Add SNS->SQS events

- docs/handel-basics/handel-file.rst
> Add notes on allowed characters in names

- docs/handel-basics/accessing-secrets.rst
- docs/index.rst
> Add initial docs for secrets access in Handel

- docs/supported-services/lambda.rst
- lib/services/lambda/index.js
- lib/services/lambda/lambda-template.yml
No other services support tagging yet. I'll be creating separate
issues for each of those services that need tagging support added
and doing them one at a time.
Resolves #68
> Add support for tagging Lambdas.

- docs/supported-services/beanstalk.rst
- lib/services/beanstalk/beanstalk-template.yml
- lib/services/beanstalk/index.js
> Add tags support for Beanstalk

- docs/supported-services/apigateway.rst
- lib/services/apigateway/apigateway-proxy-template.yml
- lib/services/apigateway/index.js
> Add support for API Gateway tags

- docs/supported-services/ecs.rst
- lib/services/ecs/ecs-service-template.yml
- lib/services/ecs/index.js
I also took advantage of this change and refactored the ECS deploy
method to be more in line with the other deployers.
Resolves #98
> Add tags support for ECS service.

- lib/util/util.js
> Fix zip bug for subdirectories

- docs/getting-started/introduction.rst
- docs/getting-started/tutorial-creating-an-app.rst
- docs/handel-basics/account-config-file.rst
- docs/index.rst
> Add first draft of a tutorial

- bin/handel
- lib/cli/index.js
> Show error for malformed handel.yml file

- lib/services/lambda/index.js
- test/services/dynamodb/dynamodb-test.js
> Add env vars from service to Lambdas

- docs/index.rst
- docs/supported-services/memcached.rst
- docs/supported-services/redis.rst
- lib/services/memcached/index.js
- lib/services/memcached/memcached-template.yml
- test/services/memcached/memcached-test.js
This service kind of was free by doing Redis, so I figured I'd
implement it while ElastiCache was fresh in my mind.
This service doesn't support snapshot or maintenance window
configuration yet.
Resolves #134
> Add initial support for Memcached service.

- docs/handel-basics/consuming-service-dependencies.rst
- docs/index.rst
- docs/supported-services/mysql.rst
- lib/aws/ssm-calls.js
- lib/services/beanstalk/index.js
- lib/services/deployers-common.js
- lib/services/ec2-sg-template.yml
- lib/services/ecs/index.js
- lib/services/memcached/index.js
- lib/services/mysql/index.js
- lib/services/mysql/mysql-template.yml
- lib/services/redis/index.js
- test/services/deployers-common-test.js
- test/services/mysql/mysql-test.js
This initial support for RDS just adds MySQL. I'll probably add
PostgreSQL soon, but I don't have any immediate plans to add
Oracle, MSSQL, or Aurora anytime soon until asked for.
Resolves #13
> Add support for MySQL service.

- lib/services/deployers-common.js
- test/services/deployers-common-test.js
> Fix bug with race condition in Beanstalk service role

- docs/supported-services/sqs.rst
- lib/services/sqs/index.js
- lib/services/sqs/sqs-template.yml
> Fix bug where receive_message_wait_time_seconds was not configurable

- lib/aws/cloudformation-calls.js
- lib/common/deploy-phase-common.js
- lib/services/apigateway/index.js
- lib/services/beanstalk/index.js
- lib/services/cloudwatchevent/index.js
- lib/services/dynamodb/index.js
- lib/services/ecs/index.js
- lib/services/efs/index.js
- lib/services/lambda/index.js
- lib/services/memcached/index.js
- lib/services/mysql/index.js
- lib/services/postgresql/index.js
- lib/services/redis/index.js
- lib/services/s3/index.js
- lib/services/s3staticsite/index.js
- lib/services/sns/index.js
- lib/services/sqs/index.js
This change adds tags to the CloudFormation stacks, including the
defaults of app and env that get applied without you adding anything
Resolves #174
> Tag CloudFormation stacks for services.

- docs/supported-services/redis.rst
- lib/services/redis/index.js
- lib/services/redis/redis-single-no-repl-template.yml
- lib/services/redis/redis-single-repl-template.yml
> added snapshot_window parameter for redis service

- docs/supported-services/redis.rst
- lib/services/redis/index.js
- lib/services/redis/redis-single-no-repl-template.yml
- lib/services/redis/redis-single-repl-template.yml
> Add support for maintenance windows

- docs/supported-services/sns.rst
- lib/services/sns/index.js
- lib/services/sns/sns-template.yml
- test/services/sns/sns-test.js
> added static subscriptions to SNS

- docs/supported-services/ecs.rst
- lib/services/ecs/ecs-service-template.yml
- lib/services/ecs/index.js
- test/services/ecs/ecs-test.js
This is a breaking change in the Handel schema. At this point I
have few enough consumers that I can do this and just manually
update those ECS services.
Resolves #193
> Add support for multiple containers

- docs/supported-services/ecs.rst
- lib/services/ecs/ecs-service-template.yml
- lib/services/ecs/index.js
> Add support for ECS container links

- docs/supported-services/apigateway.rst
- docs/supported-services/beanstalk.rst
- docs/supported-services/cloudwatchevents.rst
- docs/supported-services/iot.rst
- docs/supported-services/memcached.rst
- docs/supported-services/mysql.rst
- docs/supported-services/postgresql.rst
- docs/supported-services/redis.rst
- lib/services/apigateway/apigateway-proxy-template.yml
- lib/services/apigateway/index.js
- lib/services/beanstalk/beanstalk-template.yml
- lib/services/beanstalk/index.js
- lib/services/cloudwatchevent/event-rule-template.yml
- lib/services/cloudwatchevent/index.js
- lib/services/iot/index.js
- lib/services/iot/iot-topic-rule-template.yml
- lib/services/memcached/index.js
- lib/services/memcached/memcached-template.yml
- lib/services/mysql/index.js
- lib/services/mysql/mysql-template.yml
- lib/services/postgresql/index.js
- lib/services/postgresql/postgresql-template.yml
- lib/services/redis/index.js
- lib/services/redis/redis-single-no-repl-template.yml
- lib/services/redis/redis-single-repl-template.yml
- package.json
Some minor changes to allow for custom descriptions for various components. The mocha tests all passed.
> Add custom descriptions

- .gitignore
- docs/supported-services/beanstalk.rst
- lib/common/util.js
- lib/services/beanstalk/deployable-artifact.js
- lib/services/beanstalk/index.js
- package.json
- test/common/util-test.js
- test/services/beanstalk/deployable-artifact-test.js
Added <aws_account_id> and <aws_region> tag replacment for beanstalk Dockerrun.aws.json files
> beanstalk Dockerrun.aws.json tags

- docs/supported-services/s3.rst
- lib/services/s3/index.js
- lib/services/s3/lifecycles.js
- lib/services/s3/s3-template.yml
- test/services/s3/lifecycle-test.js
- test/services/s3/s3-test.js
This add initial support for s3 bucket lifecycle policies
resolves #169
> add S3 lifecycles support

- docs/supported-services/ecs.rst
- lib/services/ecs/containers.js
- lib/services/ecs/ecs-service-template.yml
- lib/services/ecs/index.js
- test/services/ecs/ecs-test.js
Fixes #267 . 
Logging is turned on by default.
> Add ECS CloudWatch logging

- docs/supported-services/dynamodb.rst
- lib/services/dynamodb/dynamodb-autoscaling-template.yml
- lib/services/dynamodb/index.js
- package.json
- test/services/dynamodb/dynamodb-test.js
> Dynamo auto scaling

- docs/supported-services/lambda.rst
- lib/services/lambda/index.js
- package-lock.json
> Add support for Lambda to be consumed by other services

- lib/services/ecs/index.js
- test/services/ecs/ecs-test.js
Okay, I've added the test case and tried it out. So much for a quick fix.
> Ecs bug fix

- docs/supported-services/mysql.rst
- docs/supported-services/postgresql.rst
- docs/supported-services/redis.rst
- lib/services/mysql/index.js
- lib/services/postgresql/index.js
- test/services/mysql/mysql-test.js
- test/services/postgresql/postgresql-test.js
> Require version for Postgres and MySQL

- docs/supported-services/mysql.rst
- docs/supported-services/postgresql.rst
- lib/common/delete-phases-common.js
- lib/common/deploy-phase-common.js
- lib/common/rds-deployers-common.js
- lib/services/mysql/index.js
- lib/services/mysql/mysql-template.yml
- lib/services/postgresql/index.js
- lib/services/postgresql/postgresql-template.yml
- test/common/deploy-phase-common-test.js
- test/common/rds-deployers-common-test.js
- test/services/mysql/mysql-test.js
- test/services/postgresql/postgresql-test.js
This isn't really something that should probably be committed to
source control, nor should it have a default like 'handel'. We'll
just auto-generate a pseudo-random username for databases.
Resolves #306
> Auto-generate usernames for RDS databases.

- package-lock.json
- package.json
- src/aws/ses-calls.ts
- tslint.json
Add tslint as well as a npm script for running it. Later when all files converted, can add to build script as pre-requisite.
Also updated the existing TypeScript file to follow tslint rules. Check it out @dsw88!
> Add tslint

- docs/supported-services/cloudwatchevents.rst
fixed typo and confusing example in the cloudwatch documentation
> cloudwatch documentation fix

- test/handelfile/parser-v1-test.ts
Fix test errors introduced in #364.
> Fix parser tests

- docs/supported-services/dynamodb.rst
- handel/src/services/dynamodb/config-types.ts
- handel/src/services/dynamodb/dynamodb-template.yml
- handel/src/services/dynamodb/index.ts
See http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html for details on this feature.
> Add support for DynamoDB TTL.

- docs/handel-basics/accessing-secrets.rst
- handel/src/common/deploy-phase-common.ts
- handel/src/handelfile/parser-v1.ts
- handel/test/common/deploy-phase-common-test.ts
- handel/test/handelfile/parser-v1-test.ts
> Add support for global parameters in SSM Parameter Store

- handel/src/account-config/default-account-config.ts
- handel/src/aws/cloudformation-calls.ts
- handel/src/common/deploy-phase-common.ts
- handel/src/common/pre-deploy-phase-common.ts
- handel/src/common/s3-deployers-common.ts
- handel/src/services/apigateway/proxy/proxy-passthrough-deploy-type.ts
- handel/src/services/apigateway/swagger/swagger-deploy-type.ts
- handel/src/services/beanstalk/index.ts
- handel/src/services/cloudwatchevent/index.ts
- handel/src/services/dynamodb/autoscaling.ts
- handel/src/services/dynamodb/index.ts
- handel/src/services/ecs-fargate/index.ts
- handel/src/services/ecs/cluster-auto-scaling.ts
- handel/src/services/ecs/index.ts
- handel/src/services/efs/index.ts
- handel/src/services/iot/index.ts
- handel/src/services/kms/index.ts
- handel/src/services/lambda/index.ts
- handel/src/services/memcached/index.ts
- handel/src/services/mysql/index.ts
- handel/src/services/postgresql/index.ts
- handel/src/services/redis/index.ts
- handel/src/services/route53zone/index.ts
- handel/src/services/s3/index.ts
- handel/src/services/s3staticsite/index.ts
- handel/src/services/sns/index.ts
- handel/src/services/sqs/index.ts
- handel/test/aws/cloudformation-calls-test.ts
- handel/test/common/deploy-phase-common-test.ts
> Add support for each service specifying its own create stack timeout

- handel/src/aws/cloudformation-calls.ts
> Fix bug and improve stack deploy errors output

- handel/src/common/elasticache-deployers-common.ts
- handel/test/common/elasticache-deployers-common-test.ts
> Fix bug where some app names would cause errors

- docs/supported-services/s3.rst
- docs/supported-services/sns.rst
- docs/supported-services/sqs.rst
- examples/s3-events/handel.yml
- handel/src/aws/aws-wrapper.ts
- handel/src/aws/s3-calls.ts
- handel/src/services/s3/index.ts
- handel/src/services/sns/index.ts
- handel/src/services/sqs/index.ts
- handel/test/aws/s3-calls-test.ts
- handel/test/services/lambda/lambda-test.ts
- handel/test/services/s3/s3-test.ts
- handel/test/services/sns/sns-test.ts
- handel/test/services/sqs/sqs-test.ts
> Add support for S3 events to SNS/SQS

- docs/handel-basics/account-config-file.rst
- examples/s3-static-site/handel.yml
- extension-api/extension-api.ts
- extension-api/package-lock.json
- extension-api/package.json
- handel/package-lock.json
- handel/package.json
- handel/src/account-config/account-config.ts
- handel/src/account-config/default-account-config.ts
- handel/src/cli/index.ts
- handel/src/handel.ts
- handel/src/lifecycles/check.ts
- handel/src/services/cloudwatchevent/index.ts
- handel/test/account-config/account-config-test.ts
- handel/test/account-config/default-account-config-test.ts
- handel/test/deploy/deploy-order-calc-test.ts
- handel/test/test-account-config.yml
> Make the account_id field a string in the account config file

- handel/src/services/lambda/index.ts
- handel/src/services/lambda/lambda-role-statements-vpc.handlebars
- handel/src/services/lambda/lambda-role-statements.handlebars
> Allow lambda to invoke itself

- handel/src/handelfile/parser-v1.ts
- handel/test/handelfile/parser-v1-test.ts
> Handle scoped extension packages properly

- docs/supported-services/apigateway.rst
- examples/apigateway-proxy/handel.yml
- examples/apigateway-proxy/index.js
- examples/apigateway-with-dynamodb/function1/index.js
- examples/apigateway-with-dynamodb/function2/index.js
- examples/apigateway-with-dynamodb/swagger.json
- extension-support/src/util/handlebars-utils.ts
- handel/src/aws/aws-wrapper.ts
- handel/src/aws/lambda-calls.ts
- handel/src/services/apigateway/common.ts
- handel/src/services/apigateway/config-types.ts
- handel/src/services/apigateway/proxy/apigateway-proxy-template.yml
- handel/src/services/apigateway/proxy/proxy-passthrough-deploy-type.ts
- handel/src/services/apigateway/swagger/apigateway-swagger-template.yml
- handel/src/services/apigateway/swagger/swagger-deploy-type.ts
- handel/test/aws/lambda-calls-test.ts
- handel/test/services/apigateway/common-test.ts
- handel/test/services/apigateway/proxy/proxy-passthrough-deploy-type-test.ts
- handel/test/services/apigateway/swagger/swagger-deploy-type-test.ts
- handel/test/services/apigateway/swagger/swagger-with-warmup.json
Adds the ability to schedule automatic lambda warmup calls to API Gateway resources. Optionally will make the call simulate an HTTP API Gateway Proxy request.
> Implement Automatic Lambda Warming

- docs/index.rst
- docs/supported-services/aurora.rst
- examples/aurora/handel.yml
- handel/src/services/aurora/aurora-template.yml
- handel/src/services/aurora/config-types.ts
- handel/src/services/aurora/index.ts
- handel/src/services/aurora/params-schema.json
- handel/test/services/apiaccess/apiaccess-test.ts
- handel/test/services/aurora/aurora-test.ts
- handel/test/services/codedeploy/codedeploy-test.ts
> Add Initial Support for Aurora

- handel/src/services/beanstalk/index.ts
- handel/src/services/beanstalk/params-schema.json
- handel/src/services/cloudwatchevent/params-schema.json
- handel/src/services/sns/params-schema.json
This change adds JSON schema checks for Beanstalk, and makes some additions that were missed for SNS and CloudWatch Events.
> Add more JSON schema checks

- handel/src/services/apigateway/index.ts
- handel/src/services/apigateway/params-schema.json
- handel/src/services/apigateway/proxy/proxy-passthrough-deploy-type.ts
- handel/src/services/apigateway/swagger/swagger-deploy-type.ts
- handel/test/services/apigateway/apigateway-test.ts
- handel/test/services/apigateway/proxy/proxy-passthrough-deploy-type-test.ts
This change removes the deprecated syntax for proxy passthrough, and adds a JSON schema check.
> API Gateway changes

- docs/index.rst
- docs/supported-services/aiservices.rst
- examples/aiservices/handel.yml
- examples/aiservices/index.py
- handel/src/services/aiservices/config-types.ts
- handel/src/services/aiservices/index.ts
- handel/src/services/aiservices/params-schema.json
- handel/src/services/aiservices/rekognition-statements.json
- handel/src/services/aurora/config-types.ts
- handel/src/services/codedeploy/deployable-artifact.ts
- handel/src/services/codedeploy/iam-roles.ts
- handel/src/services/dynamodb/index.ts
- handel/src/services/ecs/cluster-auto-scaling.ts
- handel/src/services/ecs/cluster.ts
- handel/test/account-config/default-account-config-test.ts
- handel/test/services/aiservices/aiservices-test.ts
- handel/test/services/mysql/mysql-test.ts
- handel/test/services/postgresql/postgresql-test.ts
This adds the initial AI services provisioner with support for the Rekognition service.
Resolves #488
> Initial AI Services Provisioner

- docs/index.rst
- docs/supported-services/neptune.rst
- examples/neptune/gremlin-console/appspec.yml
- examples/neptune/gremlin-console/scripts/install-gremlin.sh
- examples/neptune/gremlin-js/index.js
- examples/neptune/gremlin-js/package-lock.json
- examples/neptune/gremlin-js/package.json
- examples/neptune/handel.yml
- handel/src/services/neptune/config-types.ts
- handel/src/services/neptune/index.ts
- handel/src/services/neptune/neptune-template.yml
- handel/src/services/neptune/params-schema.json
- handel/test/services/neptune/neptune-test.ts
This PR adds support for the Neptune service.
Resolves #490
> Initial Neptune Provisioner

- examples/aurora/handel.yml
- examples/neptune/handel.yml
- handel/src/services/aurora/aurora-template.yml
- handel/src/services/aurora/config-types.ts
- handel/src/services/aurora/index.ts
- handel/src/services/mysql/config-types.ts
- handel/src/services/mysql/index.ts
- handel/src/services/mysql/mysql-template.yml
- handel/src/services/neptune/config-types.ts
- handel/src/services/neptune/index.ts
- handel/src/services/neptune/neptune-template.yml
- handel/src/services/postgresql/config-types.ts
- handel/src/services/postgresql/index.ts
- handel/src/services/postgresql/postgresql-template.yml
> Use lower-case names for RDS instances and clusters

- docs/index.rst
- docs/supported-services/elasticsearch.rst
- examples/elasticsearch/handel.yml
- examples/elasticsearch/lambda/index.js
- handel/src/aws/aws-wrapper.ts
- handel/src/aws/iam-calls.ts
- handel/src/services/elasticsearch/config-types.ts
- handel/src/services/elasticsearch/elasticsearch-template.yml
- handel/src/services/elasticsearch/index.ts
- handel/src/services/elasticsearch/params-schema.json
- handel/test/aws/iam-calls-test.ts
- handel/test/services/elasticsearch/elasticsearch-test.ts
> Initial support for Elasticsearch

- handel/src/services/beanstalk/index.ts
> Fix beanstalk's default SSH rule to be less permissive

- examples/ses/handel.yml
- handel/src/services/ses/index.ts
- handel/src/services/ses/params-schema.json
- handel/src/services/ses/params.schema.json
- handel/test/services/ses/ses-test.ts
> Ses schema json

- examples/route53zone/handel.yml
- handel/src/services/route53zone/index.ts
- handel/src/services/route53zone/params-schema.json
- handel/test/services/route53zone/route53zone-test.ts
> Made a schema and appropriate tests for route53zone

- examples/sqs/handel.yml
- handel/src/services/sqs/index.ts
- handel/src/services/sqs/params-schema.json
- handel/test/services/sqs/sqs-test.ts
> Sqs schema

- examples/postgresql/handel.yml
- handel/src/services/postgresql/index.ts
- handel/src/services/postgresql/params-schema.json
- handel/test/services/postgresql/postgresql-test.ts
> added JSON schema to postgresql

- examples/mysql/handel.yml
- handel/src/services/mysql/index.ts
- handel/src/services/mysql/params-schema.json
> added JSON schema to mysql

- examples/memcached/handel.yml
- handel/src/services/memcached/index.ts
- handel/src/services/memcached/params-schema.json
> added JSON schema for memcached

- examples/redis/handel.yml
- handel/src/services/redis/index.ts
- handel/src/services/redis/params-schema.json
> made a JSON schema file for redis

- examples/lambda-vpc/handel.yml
- handel/src/services/lambda/index.ts
- handel/src/services/lambda/params-schema.json
> Added JSON schema for lambda

- examples/stepfunctions/handel.yml
- handel/src/services/efs/index.ts
- handel/src/services/stepfunctions/index.ts
- handel/src/services/stepfunctions/params-schema.json
> added JSON schema to stepfunctions

- docs/supported-services/ecs.rst
- handel/src/common/ecs-containers.ts
- handel/src/common/ecs-routing.ts
- handel/src/common/ecs-service-auto-scaling.ts
- handel/src/services/ecs-fargate/index.ts
- handel/src/services/ecs-fargate/params-schema.json
- handel/src/services/ecs/index.ts
- handel/src/services/ecs/params-schema.json
- handel/test/common/ecs-containers-test.ts
- handel/test/common/ecs-routing-test.ts
- handel/test/common/ecs-service-auto-scaling-test.ts
- handel/test/services/ecs-fargate/fargate-test.ts
- handel/test/services/ecs/ecs-test.ts
- handel/test/services/s3/s3-test.ts
> Ecs fargate schema

- handel/src/common/ecs-routing.ts
- handel/src/services/ecs/index.ts
- handel/test/common/ecs-routing-test.ts
> made load_balancer required if routing is specified and vice versa

- examples/dynamodb-events/handel-test.yml
- handel/src/cli/index.ts
- handel/src/services/dynamodb/params-schema.json
- handel/test/services/dynamodb/dynamodb-test.ts
Resolves issue mentioned in the slack channel
> fixed error with regex to allow the proper number of characters

- examples/ecs/handel.yml
- examples/kms/handel.yml
- examples/s3/handel.yml
- examples/sqs/handel.yml
- examples/stepfunctions/handel.yml
- examples/stepfunctions/state_machine.yml
- handel/src/services/ecs-fargate/params-schema.json
- handel/src/services/ecs/params-schema.json
- handel/src/services/s3/params-schema.json
- handel/src/services/sqs/params-schema.json
- handel/test/services/s3/s3-test.ts
We had several JSON schema issues sneak through. This PR provides fixes for the ones we know about.
> Fixes for JSON schema issues

- handel/src/services/dynamodb/index.ts
- handel/src/services/dynamodb/params-schema.json
> made key_types case insensitive

- docs/handel-basics/consuming-service-dependencies.rst
fixed a spelling error in the documentation
> fixed typo in the handel documentation

- docs/handel-basics/consuming-service-dependencies.rst
- docs/supported-services/dynamodb.rst
- examples/dynamodb-events/handel-test.yml
- handel/src/services/dynamodb/config-types.ts
- handel/src/services/dynamodb/dynamodb-template.yml
- handel/src/services/dynamodb/params-schema.json
> Global indexes dynamodb

- docs/supported-services/aiservices.rst
- examples/aiservices/handel.yml
- handel/src/services/aiservices/index.ts
- handel/src/services/aiservices/params-schema.json
- handel/src/services/aiservices/transcribe-statements.json
- handel/test/services/aiservices/aiservices-test.ts
> added handel support for transcribe

- docs/index.rst
- docs/supported-services/amazonmq.rst
- examples/amazonmq/app.js
- examples/amazonmq/handel.yml
- examples/amazonmq/myconfig.xml
- extension-support/src/common/bind-phase.ts
- extension-support/src/common/delete-phases.ts
- handel/package-lock.json
- handel/src/services/amazonmq/amazonmq-template.yml
- handel/src/services/amazonmq/config-types.ts
- handel/src/services/amazonmq/index.ts
- handel/src/services/amazonmq/params-schema.json
This commit adds initial support for the AmazonMQ service. It has a beta tag on the docs since I haven't really used this myself yet and don't yet know if the implementation is optimal.
Resolves #573
> AmazonMQ - Add initial support

- handel/src/aws/aws-wrapper.ts
- handel/src/cli/index.ts
Handel no longer makes you wait for four minutes to tell you that you are not logged in
> Speed up check if not logged in

- handel/src/services/ecs-fargate/ecs-fargate-template.yml
- handel/src/services/ecs/ecs-service-template.yml
> Fixes the IAM role problem

- docs/handel-basics/accessing-secrets.rst
- extension-api/extension-api.ts
- extension-support/src/common/deploy-phase.ts
- extension-support/test/common/deploy-phase-test.ts
- handel/package-lock.json
This pull request adds functionality to access parameters by path. This is hopefully a first step in moving parameter usage to paths instead of dot separator
> adding ssm parameter path support

- handel/src/services/codedeploy/codedeploy-asg-template.handlebars
> add redirect to https for codedeploy

- docs/supported-services/aiservices.rst
- docs/supported-services/s3staticsite.rst
This fixes errors in the AI Service and clarifies HTTPS certificate for s3 cloudfront
closes #604
> fixing docs

- handel/src/services/ses/index.ts
ses:SendRawEmail...seriously, how many different ways are there to send email
https://byu-oit.slack.com/archives/C4515NCJ1/p1555951677038300?thread_ts=1555701431.035600&cid=C4515NCJ1
> ses:SendRawEmail

- handel/src/services/route53zone/index.ts
this corrects a bad console message
> fixing incorrect console message

- docs/supported-services/beanstalk.rst
- handel/src/services/beanstalk/config-types.ts
- handel/src/services/beanstalk/index.ts
- handel/src/services/beanstalk/params-schema.json
This is will add a patching object to elastic beanstalk.
> Added patching object
